const data = [
  {
    image: "campus-managment.jpg",
    title: "CAMPUS MANAGEMENT",
    des: "SUMS-ERP can manage unlimited campuses of a parent organization. You can access & view all of your campuses in one dashboard.",

    dialogData: {
      heading: "CAMPUS MANAGEMENT",
      image1: "campus-managment.jpg",
      image2: "campus-managment.jpg",
      image3: "campus-managment.jpg",
      para: "SUMS-ERP can manage unlimited campuses of a parent organization. You can access & view all of your campuses in one dashboard.",
      video: "asd.mp4",
    },
  },
  {
    image: "online-addmission.jpg",
    title: "ONLINE ADMISSION",
    des: "Studetns of different locations can admission online, through different social platforms. Online admission request will be received by admission depart.",
    dialogData: {
      heading: "ONLINE ADMISSION",
      image1: "online-addmission.jpg",
      image2: "online-addmission.jpg",
      image3: "online-addmission.jpg",
      para: "Studetns of different locations can admission online, through different social platforms. Online admission request will be received by admission depart.",
      video: "asd.mp4",
    },
  },
  {
    image: "analysis-chart.jpg",
    title: "ANALYSIS CHARTS",
    des: "There are many imbedded BI charts for a large data. Which will visualized your data in a graphical way.",
    dialogData: {
      heading: "asd",
      image1: "analysis-chart.jpg",
      image2: "analysis-chart.jpg",
      image3: "analysis-chart.jpg",
      para: "There are many imbedded BI charts for a large data. Which will visualized your data in a graphical way.",
      video: "asd.mp4",
    },
  },
  {
    image: "bi-tools.jpg",
    title: "BI-TOOL DASHBOARD",
    des: "SUMS-ERP can manage unlimited campuses of a parent organization. You can access & view all of your campuses in one dashboard.",
    dialogData: {
      heading: "BI-TOOL DASHBOARD",
      image1: "bi-tools.jpg",
      image2: "bi-tools.jpg",
      image3: "bi-tools.jpg",
      para: "SUMS-ERP can manage unlimited campuses of a parent organization. You can access & view all of your campuses in one dashboard.",
      video: "asd.mp4",
    },
  },
  {
    image: "fee-payment.jpg",
    title: "FEE PAYMENT",
    des: "Student can pay their fees and bills online through different payment gateways.",
    dialogData: {
      heading: "FEE PAYMENT",
      image1: "fee-payment.jpg",
      image2: "fee-payment.jpg",
      image3: "fee-payment.jpg",
      para: "Student can pay their fees and bills online through different payment gateways.",
      video: "asd.mp4",
    },
  },
  {
    image: "fee-record.jpg",
    title: "FEE RECORDS",
    des: "Management & Student can view their feerecord in their dashboards, for a transparency.",
    dialogData: {
      heading: "FEE RECORDS",
      image1: "fee-record.jpg",
      image2: "fee-record.jpg",
      image3: "fee-record.jpg",
      para: "Management & Student can view their feerecord in their dashboards, for a transparency.",
      video: "asd.mp4",
    },
  },
  {
    image: "billing.jpg",
    title: "BILLING",
    des: "Easily generate bills, and generate their pdf, xls, etc.And can share with different departments",
    dialogData: {
      heading: "BILLING",
      image1: "billing.jpg",
      image2: "billing.jpg",
      image3: "billing.jpg",
      para: "Easily generate bills, and generate their pdf, xls, etc.And can share with different departments",
      video: "asd.mp4",
    },
  },
  {
    image: "inventory.jpg",
    title: "INVENTORY",
    des: "Keep track of what’s in stock with inventory software. Populate invoices and orders with items you issue.",
    dialogData: {
      heading: "INVENTORY",
      image1: "inventory.jpg",
      image2: "inventory.jpg",
      image3: "inventory.jpg",
      para: "Keep track of what’s in stock with inventory software. Populate invoices and orders with items you issue.",
      video: "asd.mp4",
    },
  },
  {
    image: "library.jpg",
    title: "LIBRARY",
    des: "Use to maintain issue books and return. Also can generate their reports in all formats.",
    dialogData: {
      heading: "LIBRARY",
      image1: "library.jpg",
      image2: "library.jpg",
      image3: "library.jpg",
      para: "Use to maintain issue books and return. Also can generate their reports in all formats.",
      video: "asd.mp4",
    },
  },
  {
    image: "inquiry.jpg",
    title: "INQUIRIES",
    des: "For general and advance statistics repots. We canmanipulate your daily inquires of different purposes.",
    dialogData: {
      heading: "INQUIRIES",
      image1: "inquiry.jpg",
      image2: "inquiry.jpg",
      image3: "inquiry.jpg",
      para: "For general and advance statistics repots. We canmanipulate your daily inquires of different purposes.",
      video: "asd.mp4",
    },
  },
  {
    image: "complain.jpg",
    title: "COMPLAINS",
    des: "Details of all complains from students, staff, or management.",
    dialogData: {
      heading: "COMPLAINS",
      image1: "complain.jpg",
      image2: "complain.jpg",
      image3: "complain.jpg",
      para: "Details of all complains from students, staff, or management.",
      video: "asd.mp4",
    },
  },
  {
    image: "postal.jpg",
    title: "POSTALS",
    des: "Maintain records of receive and dispatch postal.",
    dialogData: {
      heading: "POSTAL",
      image1: "postal.jpg",
      image2: "postal.jpg",
      image3: "postal.jpg",
      para: "Maintain records of receive and dispatch postal.",
      video: "asd.mp4",
    },
  },
  {
    image: "petty-cash.jpg",
    title: "PETTY CASH",
    des: "Track and view flow of daily cash in a organization. Debit and credit of flow of all cash money.",
    dialogData: {
      heading: "PETTY CASH",
      image1: "petty-cash.jpg",
      image2: "petty-cash.jpg",
      image3: "petty-cash.jpg",
      para: "Track and view flow of daily cash in a organization. Debit and credit of flow of all cash money.",
      video: "asd.mp4",
    },
  },
  {
    image: "income.jpg",
    title: "INCOME",
    des: "Other income except fees. Daily bases entries of income to maintain record.",
    dialogData: {
      heading: "INCOME",
      image1: "income.jpg",
      image2: "income.jpg",
      image3: "income.jpg",
      para: "Other income except fees. Daily bases entries of income to maintain record.",
      video: "asd.mp4",
    },
  },
  {
    image: "expense.jpg",
    title: "EXPENSE",
    des: "Other expenses rather than salaries. Daily bases entriesfor record and reports.",
    dialogData: {
      heading: "EXPENSE",
      image1: "expense.jpg",
      image2: "expense.jpg",
      image3: "expense.jpg",
      para: "Other expenses rather than salaries. Daily bases entriesfor record and reports.",
      video: "asd.mp4",
    },
  },
  {
    image: "bank.jpg",
    title: "BANK RECONCILATION",
    des: "Bank reconciliation allows you to maintain your transactions history and add all transactions here.",
    dialogData: {
      heading: "BANK RECONCILATION",
      image1: "bank.jpg",
      image2: "bank.jpg",
      image3: "bank.jpg",
      para: "Bank reconciliation allows you to maintain your transactions history and add all transactions here.",
      video: "asd.mp4",
    },
  },
  {
    image: "report.jpg",
    title: "REPORTING",
    des: "Track your finances with accurate accounting reports. And collaborate with your advisor online in real time.",
    dialogData: {
      heading: "REPORTING",
      image1: "report.jpg",
      image2: "report.jpg",
      image3: "report.jpg",
      para: "Track your finances with accurate accounting reports. And collaborate with your advisor online in real time.",
      video: "asd.mp4",
    },
  },
  {
    image: "adds.jpg",
    title: "MANAGE AD's",
    des: "Manage your local ad's in SUMS-ERP. You caneasily share your ad's with all user dashboard.",
    dialogData: {
      heading: "MANAGE AD's",
      image1: "adds.jpg",
      image2: "adds.jpg",
      image3: "adds.jpg",
      para: "Manage your local ad's in SUMS-ERP. You caneasily share your ad's with all user dashboard.",
      video: "asd.mp4",
    },
  },
  {
    image: "notice.jpg",
    title: "NOTICES",
    des: "Share academic notices with Staff or Students. Daily notices will allow users to be active.",
    dialogData: {
      heading: "NOTICES",
      image1: "notice.jpg",
      image2: "notice.jpg",
      image3: "notice.jpg",
      para: "Share academic notices with Staff or Students. Daily notices will allow users to be active.",
      video: "asd.mp4",
    },
  },
  {
    image: "exam.jpg",
    title: "ONILINE EXAMS",
    des: "Easily take online exams from different sections.All students can submit their exams online throughportals.",
    dialogData: {
      heading: "ONILINE EXAMS",
      image1: "exam.jpg",
      image2: "exam.jpg",
      image3: "exam.jpg",
      para: "Easily take online exams from different sections.All students can submit their exams online throughportals.",
      video: "asd.mp4",
    },
  },
  {
    image: "lms.jpg",
    title: "LMS",
    des: "Professional and modern LMS allow you to manage your students learning. It increase communication between staff and students.",
    dialogData: {
      heading: "LMS",
      image1: "lms.jpg",
      image2: "lms.jpg",
      image3: "lms.jpg",
      para: "Professional and modern LMS allow you to manage your students learning. It increase communication between staff and students.",
      video: "asd.mp4",
    },
  },
  {
    image: "attandence.jpg",
    title: "REALTIME ATTANDACE",
    des: "Integrated attendance module will automaticallyfetch real-time data.",
    dialogData: {
      heading: "REALTIME ATTANDACE",
      image1: "attandence.jpg",
      image2: "attandence.jpg",
      image3: "attandence.jpg",
      para: "Integrated attendance module will automaticallyfetch real-time data.",
      video: "asd.mp4",
    },
  },
  {
    image: "transport.jpg",
    title: "TRANSPORT",
    des: "Manage students transport and view transporthistory.",
    dialogData: {
      heading: "TRANSPORT",
      image1: "transport.jpg",
      image2: "transport.jpg",
      image3: "transport.jpg",
      para: "Manage students transport and view transporthistory.",
      video: "asd.mp4",
    },
  },
  {
    image: "hostel.jpg",
    title: "HOSTELS",
    des: "Manage and track students hostels rooms.make student relations with hostels.",
    dialogData: {
      heading: "HOSTELS",
      image1: "hostel.jpg",
      image2: "hostel.jpg",
      image3: "hostel.jpg",
      para: "Manage and track students hostels rooms.make student relations with hostels.",
      video: "asd.mp4",
    },
  },
  {
    image: "clearnace.jpg",
    title: "STUDENT CLEARANCE",
    des: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
    dialogData: {
      heading: "STUDENT CLEARANCE",
      image1: "clearnace.jpg",
      image2: "clearnace.jpg",
      image3: "clearnace.jpg",
      para: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
      video: "asd.mp4",
    },
  },
  {
    image: "certificate.jpg",
    title: "CERTIFICATES",
    des: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
    dialogData: {
      heading: "CERTIFICATES",
      image1: "certificate.jpg",
      image2: "certificate.jpg",
      image3: "certificate.jpg",
      para: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
      video: "asd.mp4",
    },
  },
  {
    image: "evaluation.jpg",
    title: "EVALUATION FORMS",
    des: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
    dialogData: {
      heading: "EVALUATION FORMS",
      image1: "evaluation.jpg",
      image2: "evaluation.jpg",
      image3: "evaluation.jpg",
      para: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
      video: "asd.mp4",
    },
  },
  {
    image: "integration.jpg",
    title: "INTEGRATIONS",
    des: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
    dialogData: {
      heading: "INTEGRATIONS",
      image1: "integration.jpg",
      image2: "integration.jpg",
      image3: "integration.jpg",
      para: "First of All we need to Desing academics structure and flow. Which will be followed by SUMS-ERP.",
      video: "asd.mp4",
    },
  },
];

export default data;
